# Generated by Django 5.2.7 on 2025-10-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutdescription_history_leadership_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('image', models.ImageField(upload_to='about_headers/')),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'About Header Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
