# Generated by Django 5.2.7 on 2025-10-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutheaderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Events', max_length=200)),
                ('image', models.ImageField(upload_to='events_headers/')),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Events Header Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
