# Generated by Django 5.2.7 on 2025-10-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactinfo_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomHeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Rooms Header', max_length=200)),
                ('image', models.ImageField(upload_to='headers/')),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle text', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Room Header Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
