# Generated by Django 5.2.7 on 2025-10-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_roomheaderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_title', models.CharField(default='Welcome!', max_length=200)),
                ('welcome_description', models.TextField(default='Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.')),
                ('photos_title', models.CharField(default='Photos', max_length=200)),
                ('photos_description', models.TextField(default='Explore our beautiful hotel through these stunning photographs showcasing our facilities, rooms, and amenities.')),
                ('menu_title', models.CharField(default='Our Unique Menu', max_length=200)),
                ('menu_description', models.TextField(default='Experience culinary excellence with our diverse menu featuring the finest ingredients and innovative dishes prepared by our expert chefs.')),
                ('testimonials_title', models.CharField(default='What Our Guests Say', max_length=200)),
                ('events_title', models.CharField(default='Latest Events', max_length=200)),
                ('events_description', models.TextField(default='Stay updated with our latest events and happenings. Join us for memorable experiences.')),
                ('learn_more_text', models.CharField(default='Learn More', max_length=100)),
                ('learn_more_link', models.URLField(blank=True, default='#')),
                ('meta_title', models.CharField(default='Cinnamon Chalet - Luxury Hotel & Resort', max_length=200)),
                ('meta_description', models.TextField(default='Experience luxury accommodation at Cinnamon Chalet. Enjoy premium amenities, exquisite dining, and unforgettable stays in a serene environment.')),
                ('meta_keywords', models.CharField(default='luxury hotel, resort, accommodation, dining, events', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
    ]
