# Generated by Django 5.2.7 on 2025-10-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_newslettersubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
