# Generated by Django 5.2.7 on 2025-10-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactheaderimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactHeaderImage',
        ),
    ]
